### PR TITLE
Add to .gitignore: .idea project files

### PR DESCRIPTION
**Pull request by Niehaus**
### :page_facing_up: Release Notes

- Added to .gitignore: .idea project files

### CODE REVIEW

**Comment by beraldoleal** [comment]
This is user-specific files, should not be here, IMO.

**Comment by hdiogenes** [comment]
I think she was just following the other projects, @beraldoleal. Python-OpenFlow and Kytos both have "spyder project" "rope project", etc. on .gitignore. If the standard will be to not include IDE-specific listings, I think we should remove those, too. Reopening here until we settle this down.

**Comment by beraldoleal** [comment]
We should remove the files there. Having specific user files in .gitignore is not a good idea, IMO. If every single contributor decides to use a different IDE or having different files in the project folder, .gitignore will be huge.

**Review by beraldoleal — CHANGES_REQUESTED** [review]
Left a small comment about this, on issue thread.

**Comment by rmotitsuki** [comment]
Perhaps each developer should configure their own global .gitignore file, so they can ignore files specific to their environment and not specific to the project.

Example:
IDE-generated files (.idea, *.iml, eclipse files, visual studio files..)
OS-generated files (Thumbs.db, DS_Store…)

Atlassian [global-git-ignore-rules](https://www.atlassian.com/git/tutorials/saving-changes/gitignore#global-git-ignore-rules)

**Comment by hdiogenes** [comment]
OK, so let's just agree on this standard and remove IDE-specific lines from the other projects. Closing here.

**Pull request closed without merging**
